development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: employee_development
  pool: 5
  username: root
  password: root


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: employee_test
  pool: 5
  username: root
  password: root


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: employee_production
  pool: 5
  username: root
  password: root

